### ISSUE TITLE
Review and correct (if needed) the new Wiki Home

### ISSUE THREAD

**Issue by pzaino** [RISC-OS-Community/DME-Core#16]
### Background

@RISC-OS-Community/code-reviews-team / @RISC-OS-Community/docs-team ,
If someone has time, could you please review and correct the new Wiki Home for the DME Project?

link here: https://github.com/RISC-OS-Community/DME-Core/wiki

Thanks!

### Definition of Done

- [x] Task A is done when. the wiki page is reviewed :) 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by skymandr** [comment]
I have had a look and updated the wiki a bit. Looks good to me.

**Comment by pzaino** [comment]
Thanks @skymandr for your help!

Closing this issue as fully resolved :)
